### ISSUE TITLE
The call_to_action text color doesn't adapt to the background

### ISSUE THREAD

**Issue by ant-ds** [imsks/On-Board-Me#1]
"Get started" is hardcoded on `Color(0xFF5B16D0)` instead of changing with the background color.

**Comment by imsks** [comment]
Yes, a few things are still hardcoded. I wasn't able to get customized all the parts of the package.
 If you want to contribute to the project, create a branch, and then create a pull request.

**Comment by imsks** [comment]
Closing because of no response. If you find yourself on this page with the same issue, you can contribute to the project. I am currently involved in other projects. I will fix it in the mean time.
