### ISSUE TITLE
Skip button

### ISSUE THREAD

**Issue by alhaaan97** [imsks/On-Board-Me#2]
how do i use the skip button or get started button?

**Comment by imsks** [comment]
You need to provide the home route for that. 
Like` homeRoute: '/Home/',` so when the user clicks on either Get Started or Skip they land on homeRoute screen.

**Comment by alhaaan97** [comment]
Thankyou for replying sir. i provided the home route and the skip button
still doesn't work.

**Comment by imsks** [comment]
Did you add routes in your main.dart because it'll finally match with those routes only?

**Comment by alhaaan97** [comment]
It WORKEDD!!!! thankyouu. amazing package
